/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

/**
 *
 * @author ageudepetris
 */
public class MainView extends javax.swing.JFrame {

    /**
     * Creates new form MainView
     */
    public MainView() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        barra_box = new javax.swing.JMenuBar();
        members_menu = new javax.swing.JMenu();
        member_man_menu = new javax.swing.JMenuItem();
        trainer_menu = new javax.swing.JMenu();
        trainer_man_menu = new javax.swing.JMenuItem();

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("GymBro Management");
        setBackground(new java.awt.Color(51, 153, 0));

        members_menu.setText("Members");
        members_menu.setFont(new java.awt.Font(".AppleSystemUIFont", 0, 13)); // NOI18N

        member_man_menu.setText("Members Management");
        member_man_menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                member_man_menuActionPerformed(evt);
            }
        });
        members_menu.add(member_man_menu);

        barra_box.add(members_menu);

        trainer_menu.setText("Trainers");
        trainer_menu.setFont(new java.awt.Font(".AppleSystemUIFont", 0, 13)); // NOI18N

        trainer_man_menu.setText("Trainers Management");
        trainer_man_menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                trainer_man_menuActionPerformed(evt);
            }
        });
        trainer_menu.add(trainer_man_menu);

        barra_box.add(trainer_menu);

        setJMenuBar(barra_box);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 277, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void member_man_menuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_member_man_menuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_member_man_menuActionPerformed

    private void trainer_man_menuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_trainer_man_menuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_trainer_man_menuActionPerformed

    /**
     * @param args the command line arguments
     */
    
        
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JMenuBar barra_box;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    public javax.swing.JMenuItem member_man_menu;
    public javax.swing.JMenu members_menu;
    public javax.swing.JMenuItem trainer_man_menu;
    public javax.swing.JMenu trainer_menu;
    // End of variables declaration//GEN-END:variables
}
